FROM node:20-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

FROM node:20-bookworm-slim AS builder
WORKDIR /app
ARG NODE_ENV=production
ARG PORT=3000
ARG DATABASE_URL
ARG N8N_BASE_URL
ARG N8N_API_KEY
ARG N8N_WEBHOOK_CANDIDATO_SYNC
ARG N8N_WEBHOOK_QRCODE_BRUNEX
ARG N8N_WEBHOOK_GOVERNANCA_BRUNEX
ARG N8N_WEBHOOK_FUNIL_BRUNEX
ARG N8N_WEBHOOK_CADENCIA_BRUNEX
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV NEXT_TELEMETRY_DISABLED=1
ENV DATABASE_URL=$DATABASE_URL
ENV N8N_BASE_URL=$N8N_BASE_URL
ENV N8N_API_KEY=$N8N_API_KEY
ENV N8N_WEBHOOK_CANDIDATO_SYNC=$N8N_WEBHOOK_CANDIDATO_SYNC
ENV N8N_WEBHOOK_QRCODE_BRUNEX=$N8N_WEBHOOK_QRCODE_BRUNEX
ENV N8N_WEBHOOK_GOVERNANCA_BRUNEX=$N8N_WEBHOOK_GOVERNANCA_BRUNEX
ENV N8N_WEBHOOK_FUNIL_BRUNEX=$N8N_WEBHOOK_FUNIL_BRUNEX
ENV N8N_WEBHOOK_CADENCIA_BRUNEX=$N8N_WEBHOOK_CADENCIA_BRUNEX
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-bookworm-slim AS runner
WORKDIR /app
ARG NODE_ENV=production
ARG PORT=3000
ARG DATABASE_URL
ARG N8N_BASE_URL
ARG N8N_API_KEY
ARG N8N_WEBHOOK_CANDIDATO_SYNC
ARG N8N_WEBHOOK_QRCODE_BRUNEX
ARG N8N_WEBHOOK_GOVERNANCA_BRUNEX
ARG N8N_WEBHOOK_FUNIL_BRUNEX
ARG N8N_WEBHOOK_CADENCIA_BRUNEX
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV NEXT_TELEMETRY_DISABLED=1
ENV DATABASE_URL=$DATABASE_URL
ENV N8N_BASE_URL=$N8N_BASE_URL
ENV N8N_API_KEY=$N8N_API_KEY
ENV N8N_WEBHOOK_CANDIDATO_SYNC=$N8N_WEBHOOK_CANDIDATO_SYNC
ENV N8N_WEBHOOK_QRCODE_BRUNEX=$N8N_WEBHOOK_QRCODE_BRUNEX
ENV N8N_WEBHOOK_GOVERNANCA_BRUNEX=$N8N_WEBHOOK_GOVERNANCA_BRUNEX
ENV N8N_WEBHOOK_FUNIL_BRUNEX=$N8N_WEBHOOK_FUNIL_BRUNEX
ENV N8N_WEBHOOK_CADENCIA_BRUNEX=$N8N_WEBHOOK_CADENCIA_BRUNEX
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/external-workflows-snapshot ./external-workflows-snapshot
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000
CMD ["npm", "run", "start"]
